if !defined? INCLUDE_IMPULSE_REQUIRES
  qaautomation_dir = "#{ENV['QAAUTOMATION_TOOLS']}/QAAutomation"
  qaautomation_finders_dir = ENV['QAAUTOMATION_FINDERS']

  require "#{qaautomation_dir}/dsl/Browser/src/browser_requires.rb"
  require "#{qaautomation_finders_dir}/Impulse/src/impulse_override_finder"

  require "#{qaautomation_finders_dir}/Common/Services/src/SOAP/services_requires"
  require "#{qaautomation_finders_dir}/Common/Services/src/REST/services_requires"

  require "#{qaautomation_finders_dir}/Impulse/src/impulse_search_product_list"
  require "#{qaautomation_finders_dir}/Impulse/src/impulse_featured_product_list"
  require "#{qaautomation_finders_dir}/Impulse/src/impulse_tabbed_product_list"
  require "#{qaautomation_finders_dir}/Impulse/src/impulse_selector"
  require "#{qaautomation_finders_dir}/Impulse/src/impulse_html_finder"
  require "#{qaautomation_finders_dir}/Impulse/src/impulse_cart_finder"
  require "#{qaautomation_finders_dir}/Impulse/src/impulse_cart_list"
  require "#{qaautomation_finders_dir}/Impulse/src/impulse_radio_buttons"
  require "#{qaautomation_finders_dir}/Impulse/src/impulse_login_create_panel"
  require "#{qaautomation_finders_dir}/Impulse/src/impulse_account_info_finder"
  require "#{qaautomation_finders_dir}/Impulse/src/impulse_checkout_finder"
  require "#{qaautomation_finders_dir}/Impulse/src/impulse_product_detail_finder"
  require "#{qaautomation_finders_dir}/Impulse/src/impulse_search_finder"
  require "#{qaautomation_finders_dir}/Impulse/src/impulse_order_history_finder"
  require "#{qaautomation_finders_dir}/Impulse/src/impulse_item_already_registered_panel"
  require "#{qaautomation_finders_dir}/Impulse/src/impulse_header_footer_finder"
  require "#{qaautomation_finders_dir}/Impulse/src/impulse_header_footer_list"
  require "#{qaautomation_finders_dir}/Impulse/src/impulse_hero_featured_right_column_finder"
  require "#{qaautomation_finders_dir}/Impulse/src/impulse_hero_featured_right_column_list"
  require "#{qaautomation_finders_dir}/Impulse/src/impulse_store_front_reports_finder"
  require "#{qaautomation_finders_dir}/Impulse/src/impulse_community_finder"
  require "#{qaautomation_finders_dir}/Impulse/src/impulse_forums_finder"
  require "#{qaautomation_finders_dir}/Impulse/src/impulse_forums_post_list"
  require "#{qaautomation_finders_dir}/Impulse/src/impulse_forums_create_reply_post_panel"
  require "#{qaautomation_finders_dir}/Impulse/src/impulse_eula_panel"
  require "#{qaautomation_finders_dir}/Impulse/src/impulse_developer_finder"
  require "#{qaautomation_finders_dir}/Impulse/src/impulse_fraud_finder"
  require "#{qaautomation_finders_dir}/Impulse/src/impulse_fraud_list"
  require "#{qaautomation_finders_dir}/Impulse/src/impulse_cart_total_panel"
  require "#{qaautomation_finders_dir}/Impulse/src/impulse_discount_links_list"
  require "#{qaautomation_finders_dir}/Impulse/src/impulse_support_finder"
  require "#{qaautomation_finders_dir}/Impulse/src/impulse_tiny_mce"
  require "#{qaautomation_finders_dir}/Impulse/src/impulse_paypal_finder"
  require "#{qaautomation_finders_dir}/Impulse/src/impulse_about_finder"
  require "#{qaautomation_finders_dir}/Impulse/src/impulse_redemption_finder"

  require "#{qaautomation_finders_dir}/Impulse/src/impulse_browser_modules"
  INCLUDE_IMPULSE_REQUIRES = false
end
